### PR TITLE
Esphome climate add action

### PR DESCRIPTION
**Pull request by marcelveldt**
as discussed in https://github.com/esphome/feature-requests/issues/392

adds action as additional property for climate component

### CODE REVIEW

**Comment by marcelveldt** [comment]
These are the changes for the hass component:
https://github.com/marcelveldt/home-assistant/commit/e7088c59cfe4d6f4d6241a7cd62caccfed1521c4

**Comment by marcelveldt** [comment]
@OttoWinter any chance to have a look at my proposed changes to include the hvac_action in the thermostat attributes ?

**Comment by OttoWinter** [comment]
Ok, merged and released in 2.3.0 🎉

**Comment by marcelveldt** [comment]
Thanks!

**Pull request merged**
