### PR TITLE
Add entity attribute to Home Assistant state subscriptions

### PR DESCRIPTION
**Pull request by frenck**
This is the first step needed in order to add support for Home Assistant entity attributes in ESPHome.

Feature request: esphome/feature-requests#1112

### CODE REVIEW

**Comment by frenck** [comment]
Done testing now. Ready for review.

**Review by jesserockz — APPROVED** [review]

**Comment by frenck** [comment]
Thanks, @jesserockz!

Anything needed to merge/release this at this point?

I would need a bump on this repo in order to start setting up PRs on the end of Home Assistant.

../Frenck

**Comment by frenck** [comment]
Thanks, @jesserockz ❤️

**Comment by jli113** [comment]
It's a great feature, but how does this work?
I used ESPHome to connect Xiaomi LYWSD03MMC senors (default firmware) as the given example:
sensor:
  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:B1:CD:7F"
    bindkey: "eef418daf699a0c188f3bfd17e4565d9"
    temperature:
      name: "LYWSD03MMC Temperature"
    humidity:
      name: "LYWSD03MMC Humidity"
    battery_level:
      name: "LYWSD03MMC Battery Level"
Where should I put the attribute?

**Comment by jesserockz** [comment]
Please don't ask for help on old PRs. There are many other places to ask for help and this PR has nothing to do with that code you pasted.

**Pull request merged**
