### PR TITLE
add pairing methods

### PR DESCRIPTION
**Pull request by jagheterfredrik**
relates to https://github.com/esphome/esphome/pull/4475

### CODE REVIEW

**Comment by bdraco** [comment]
We need to be able to give feedback to the API caller if the pairing was successful or not

https://github.com/home-assistant/core/pull/88603/files#diff-972150b31eac2d4abbf3a9e71009b8ed20d32b4ae0c89253fc74d2248d5b6d1dR394

**Comment by jagheterfredrik** [comment]
I'm not sure we do: https://bleak.readthedocs.io/en/latest/api/client.html#bleak.BleakClient.pair

**Comment by bdraco** [comment]
https://github.com/esphome/esphome/pull/4475#pullrequestreview-1309388432

**Comment by jagheterfredrik** [comment]
@bdraco Thoughts? 🙏

**Comment by bdraco** [comment]
Ideally we would get the failure reason code to bubble up so when we get a failure report we don't have to ask someone to dig thorough the logs on their esphome console

https://github.com/jagheterfredrik/esphome/blob/a8e89fb37117e26372dbe242d51386c49f088918/esphome/components/esp32_ble_client/ble_client_base.cpp?rgh-link-date=2023-02-22T15%3A03%3A10Z#L262

**Comment by jagheterfredrik** [comment]
I feel like I might be bloating the BluetoothDeviceConnectionResponse type at that point. Should I just make a new cb for pairing specifically like we discussed in the other PR?

**Comment by bdraco** [comment]
> Should I just make a new cb for pairing specifically like we discussed in the other PR?

Yes. Most devices won't need it so it seems like it should be it's own thing

**Comment by bdraco** [comment]
LGTM. Will need Jesse's feedback on the esphome PR before we can merge this.

**Comment by jagheterfredrik** [comment]
Thanks @bdraco, I'll clean up and test

**Comment by jagheterfredrik** [comment]
The proto did not compile as cleanly here as it did for esphome, not sure if it's using some older protoc version?

**Comment by bdraco** [comment]
> The proto did not compile as cleanly here as it did for esphome, not sure if it's using some older protoc version?

Use the docker command in the GitHub actions file

**Comment by jagheterfredrik** [comment]
Ah ofc cheers

**Review by bdraco — APPROVED** [review]
Should be good to merge once the esphome PR is approved. This may need to change a bit based on feedback from Jesse. He is on the other side of the dateline so probably will be a few days before you get feedback there.

**Review by jesserockz — APPROVED** [review]

**Pull request merged**
