### PR TITLE
Avoid executor jump to resolve ip addresses

### PR DESCRIPTION
**Pull request by bdraco**
Similar to #26

Avoids executor overload at statup with lots of esphome devices

2021-09-17 07:34:00 DEBUG (MainThread) [homeassistant.util.executor] Calling executor with function: <function getaddrinfo at 0x7f96b7915a60>, args: (192.168.107.189, 6053, 0, 0, 6, 0), kwargs: {}
2021-09-17 07:34:00 DEBUG (MainThread) [homeassistant.util.executor] Calling executor with function: <function getaddrinfo at 0x7f96b7915a60>, args: (192.168.107.248, 6053, 0, 0, 6, 0), kwargs: {}
2021-09-17 07:34:00 DEBUG (MainThread) [homeassistant.util.executor] Calling executor with function: <function getaddrinfo at 0x7f96b7915a60>, args: (192.168.107.234, 6053, 0, 0, 6, 0), kwargs: {}
2021-09-17 07:34:00 DEBUG (MainThread) [homeassistant.util.executor] Calling executor with function: <function getaddrinfo at 0x7f96b7915a60>, args: (192.168.107.206, 6053, 0, 0, 6, 0), kwargs: {}
2021-09-17 07:34:00 DEBUG (MainThread) [homeassistant.util.executor] Calling executor with function: <function getaddrinfo at 0x7f96b7915a60>, args: (192.168.107.220, 6053, 0, 0, 6, 0), kwargs: {}
2021-09-17 07:34:00 DEBUG (MainThread) [homeassistant.util.executor] Calling executor with function: <function getaddrinfo at 0x7f96b7915a60>, args: (192.168.107.61, 6053, 0, 0, 6, 0), kwargs: {}
2021-09-17 07:34:00 DEBUG (MainThread) [homeassistant.util.executor] Calling executor with function: <function getaddrinfo at 0x7f96b7915a60>, args: (192.168.107.133, 6053, 0, 0, 6, 0), kwargs: {}
2021-09-17 07:34:00 DEBUG (MainThread) [homeassistant.util.executor] Calling executor with function: <function getaddrinfo at 0x7f96b7915a60>, args: (192.168.107.3, 6053, 0, 0, 6, 0), kwargs: {}
2021-09-17 07:34:00 DEBUG (MainThread) [homeassistant.util.executor] Calling executor with function: <function getaddrinfo at 0x7f96b7915a60>, args: (192.168.107.203, 6053, 0, 0, 6, 0), kwargs: {}
2021-09-17 07:34:00 DEBUG (MainThread) [homeassistant.util.executor] Calling executor with function: <function getaddrinfo at 0x7f96b7915a60>, args: (192.168.107.178, 6053, 0, 0, 6, 0), kwargs: {}
2021-09-17 07:34:00 DEBUG (MainThread) [homeassistant.util.executor] Calling executor with function: <function getaddrinfo at 0x7f96b7915a60>, args: (192.168.107.173, 6053, 0, 0, 6, 0), kwargs: {}
2021-09-17 07:34:00 DEBUG (MainThread) [homeassistant.util.executor] Calling executor with function: <function getaddrinfo at 0x7f96b7915a60>, args: (192.168.106.243, 6053, 0, 0, 6, 0), kwargs: {}
2021-09-17 07:34:00 DEBUG (MainThread) [homeassistant.util.executor] Calling executor with function: <function getaddrinfo at 0x7f96b7915a60>, args: (192.168.107.170, 6053, 0, 0, 6, 0), kwargs: {}

### CODE REVIEW

**Comment by bdraco** [comment]
Tested on HASS Dev with manually upgrading to this version.

My esphome devices still work and no executor use on startup

**Comment by bdraco** [comment]
Using a custom `def submit` in the thread pool to watch executor calls : https://github.com/bdraco/home-assistant/blob/integration/homeassistant/util/executor.py#L65

**Comment by bdraco** [comment]
Reduced esphome startup time from `23.12 s` to `9.63 s` on one of my production installs

**Comment by OttoWinter** [comment]
> Reduced esphome startup time from `23.12 s` to `9.63 s` on one of my production installs
> 
> 

😱 how many esphome devices do you have???

I know the threadpool isn't very fast (or rather the synchronization) but I never expected it to be that slow. Do you know how much latency I can expect from executor calls?

**Review by OttoWinter — APPROVED** [review]

**Comment by bdraco** [comment]
The install I was testing on had 42.  The executor execution is really quick except when there are a lot of sync integrations competing for it at startup.   If esphome is unlucky enough to startup when the executor is in an overload state everything would wait.  Once we hit 64 workers everything grinds to a halt that is waiting for the executor even if the executor job itself will be quick because it may be in line behind one that is not.  (https://github.com/home-assistant/core/blob/dev/homeassistant/runner.py#L28).

**Pull request merged**
