### PR TITLE
Add support for fan preset modes

### PR DESCRIPTION
**Pull request by mill1000**
In order to support https://github.com/esphome/feature-requests/issues/1661, update the ListEntitiesFanResponse, FanStateResponse and FanCommandRequest with fields necessary to implement preset modes for fan entities.

(Draft) PR for ESPHome: https://github.com/esphome/esphome/pull/5694

HA PR https://github.com/home-assistant/core/pull/103781

### CODE REVIEW

**Comment by bdraco** [comment]
Is there an esphome PR to go with this?

**Comment by mill1000** [comment]
No, not yet. I (perhaps incorrectly) assumed the API was the first place to start as I understood protobufs to be backwards compatible

**Review by bdraco — APPROVED** [review]
Looks good. May need to change if https://github.com/esphome/esphome/pull/5694 changes

**Review by bdraco — APPROVED** [review]

**Comment by bdraco** [comment]
I think this is probably ok to merge soon after I retest https://github.com/esphome/esphome/pull/5694 first just to make sure there isn't likely to be any more changes needed here

**Comment by mill1000** [comment]
I agree. The API itself has been stable through most the churn in the ESPHome PR

**Comment by bdraco** [comment]
Tested the esphome PR again. All good.

This isn't likely to change so lets get it published

**Review by bdraco — APPROVED** [review]

**Pull request merged**
