### PR TITLE
Adjust ping timeout to prevent premature disconnections

### PR DESCRIPTION
**Pull request by bdraco**
Refactor keep alive to avoid coroutines which makes cancelation and disconnect a lot simpler since we don't have to worry about the complexity of canceling a task.

The ping pong timeout was 10s with a send frequency of 15s. This change increases the keep alive frequency to 20.0s and raises the default no response timeout to be 90s (4.5x the keep alive frequency). 20s was chosen because its about the time it takes for the esp device to reboot and reconnect to the network.

 This helps devices that may not have the best connection or are using some type of wifi power management aka `power_save_mode: LIGHT`.

The timeout is slightly more half of the time in the esphome code base, https://github.com/esphome/esphome/blob/df3f13ded884682dfbcbba542d79aedb1e100b0a/esphome/components/api/api_connection.cpp#L99 . In testing we didn't need the full 150s the esphome code is using since after ~90s its relatively clear that the connection has dropped.

We likely have been prematurely disconnecting for some time as we didn't report quite a few unexpected disconnects in the log until recent versions https://github.com/home-assistant/core/issues/89047#issuecomment-1454935372 :

Previous version of `_report_fatal_error` logged nothing
https://github.com/esphome/aioesphomeapi/blob/527420464da223c05fd5d054ec0a9cd891e3bec6/aioesphomeapi/connection.py#L452

Current version
https://github.com/esphome/aioesphomeapi/blob/31b75be915354c524336e6bdaf213b85d1a8038a/aioesphomeapi/connection.py#L575

fixes https://github.com/home-assistant/core/issues/85062
fixes https://github.com/home-assistant/core/issues/88535
fixes https://github.com/home-assistant/core/issues/89047

### CODE REVIEW

**Comment by nagyrobi** [comment]
Would be nice to be able to get a status of this on the ESPHome side (as a binary sensor). See https://github.com/esphome/feature-requests/issues/1656

Because there are real use cases when is needed to address the situation when HA goes down, the automations in the ESPHome node have to be aware of that.

**Comment by nagyrobi** [comment]
What I did to "manually" check: https://github.com/esphome/feature-requests/issues/2108#issuecomment-1423905640

**Comment by bdraco** [comment]
> Because there are real use cases when is needed to address the situation when HA goes down, the automations in the ESPHome node have to be aware of that.

If HA abruptly disconnects and doesn't come back for a while there is no way for the esphome device to know its gone away unless it doesn't respond go a ping since there is nothing coming back and forth over the wire.  It can't distinguish and idle connection from a dead connection unless HA comes back up and sends a TCP RST because esphome is still trying to talk over a closed connection. If its truely dead there is nothing to tell the esphome device that its offline.

The keep alive on the esphome side will eventually see that HA isn't responding and disconnect it here
https://github.com/esphome/esphome/blob/df3f13ded884682dfbcbba542d79aedb1e100b0a/esphome/components/api/api_connection.cpp#L105

**Comment by bdraco** [comment]
```
2023-03-04 08:51:02.323 DEBUG (MainThread) [aioesphomeapi.connection] 192.168.106.43: Sending <class 'api_pb2.PingRequest'>: 
2023-03-04 08:51:02.323 DEBUG (MainThread) [aioesphomeapi._frame_helper] Sending frame 4a4bf3fbdfd2fc478dbdfc6c7011454f8c381c62
2023-03-04 08:51:17.324 DEBUG (MainThread) [aioesphomeapi.connection] m5stackatomproxy @ 192.168.106.43: PingResponse (pong) was not received since last keep alive after 15.0 seconds; rescheduling keep alive
2023-03-04 08:51:32.325 DEBUG (MainThread) [aioesphomeapi.connection] m5stackatomproxy @ 192.168.106.43: PingResponse (pong) was not received since last keep alive after 15.0 seconds; rescheduling keep alive
2023-03-04 08:51:39.824 DEBUG (MainThread) [aioesphomeapi.connection] m5stackatomproxy @ 192.168.106.43: Ping response not received after 37.5 seconds
2023-03-04 08:51:39.824 WARNING (MainThread) [aioesphomeapi.connection] m5stackatomproxy @ 192.168.106.43: Connection error occurred: Ping response not received after 37.5 seconds
2023-03-04 08:51:39.827 DEBUG (MainThread) [aioesphomeapi.connection] Cleaning up connection to m5stackatomproxy @ 192.168.106.43
2023-03-04 08:51:39.828 DEBUG (MainThread) [aioesphomeapi.connection] Cleaning up connection to m5stackatomproxy @ 192.168.106.43
2023-03-04 08:51:39.828 INFO (MainThread) [aioesphomeapi.reconnect_logic] Disconnected from ESPHome API for m5stackatomproxy @ 192.168.106.43
2023-03-04 08:51:39.834 DEBUG (MainThread) [aioesphomeapi.connection] m5stackatomproxy @ 192.168.106.43: Connecting to 192.168.106.43:6053 (AddrInfo(family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, proto=6, sockaddr=IPv4Sockaddr(address='192.168.106.43', port=6053)))
2023-03-04 08:52:09.819 DEBUG (MainThread) [aioesphomeapi.connection] Cleaning up connection to m5stackatomproxy @ 192.168.106.43
2023-03-04 08:52:09.820 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for m5stackatomproxy @ 192.168.106.43: Timeout while connecting to ('192.168.106.43', 6053)
2023-03-04 08:52:09.822 INFO (MainThread) [aioesphomeapi.reconnect_logic] Trying to reconnect to m5stackatomproxy @ 192.168.106.43 in the background
2023-03-04 08:52:09.822 DEBUG (MainThread) [aioesphomeapi.reconnect_logic] Retrying m5stackatomproxy @ 192.168.106.43 in 2 seconds
2023-03-04 08:52:11.132 DEBUG (MainThread) [aioesphomeapi.reconnect_logic] m5stackatomproxy @ 192.168.106.43: Triggering reconnect because of received mDNS record record[ptr,in,_esphomelib._tcp.local.]=4500/4499,m5stackatomproxy._esphomelib._tcp.local.
2023-03-04 08:52:11.133 DEBUG (MainThread) [aioesphomeapi.connection] m5stackatomproxy @ 192.168.106.43: Connecting to 192.168.106.43:6053 (AddrInfo(family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, proto=6, sockaddr=IPv4Sockaddr(address='192.168.106.43', port=6053)))
2023-03-04 08:52:11.468 DEBUG (MainThread) [aioesphomeapi.connection] 192.168.106.43: Opened socket
2023-03-04 08:52:11.470 DEBUG (MainThread) [aioesphomeapi._frame_helper] Sending frame 
2023-03-04 08:52:11.498 DEBUG (MainThread) [aioesphomeapi._frame_helper] Sending frame 00bfede6e31e5fc4fd9241bcff4ec24a89a52142751258b6697502e2497b1c376628d070d4de9714cdcbc8fe18ac3ddb0d
2023-03-04 08:52:11.652 DEBUG (MainThread) [aioesphomeapi._frame_helper] Starting handshake...
2023-03-04 08:52:11.654 DEBUG (MainThread) [aioesphomeapi._frame_helper] Handshake complete
2023-03-04 08:52:11.654 DEBUG (MainThread) [aioesphomeapi.connection] 192.168.106.43: Sending <class 'api_pb2.HelloRequest'>: client_info: "Home Assistant 2023.4.0.dev0"
api_version_major: 1
```

**Comment by nagyrobi** [comment]
> The keep alive on the esphome side will eventually see that HA isn't responding and disconnect it here

The problem is that ESPHome currently doesn't expose it as a binary sensor.
What it does expose, is something else, which doesn't differentiate between HA or a remote logger being connected :(

**Comment by bdraco** [comment]
> > The keep alive on the esphome side will eventually see that HA isn't responding and disconnect it here
> 
> The problem is that ESPHome currently doesn't expose it as a binary sensor. What it does expose, is something else, which doesn't differentiate between HA or a remote logger being connected :(

That makes sense but its definitely out of scope for this PR

**Comment by nagyrobi** [comment]
> That makes sense but its definitely out of scope for this PR

Sure! @jesserockz

**Comment by bdraco** [comment]
related issue https://github.com/esphome/issues/issues/1194#issuecomment-706079705

**Comment by nagyrobi** [comment]
> I think it might make sense to make the HA side the exact same as the esphome side

How about handling it dynamically? For example, if `power_save_mode` is `LIGHT`, use 30s. If `HIGH`, use 60s. If no power saving present (`NONE`), use 10s. On both sides (the API could read the value from the node).
This way we could still keep it snappy for the ones not wanting to save power but need faster decisions.

**Comment by bdraco** [comment]
> > I think it might make sense to make the HA side the exact same as the esphome side
> 
> 
> 
> How about handling it dynamically? For example, if `power_save_mode` is `LIGHT`, use 30s. If `HIGH`, use 60s. If no power saving present (`NONE`), use 10s. With Ethernet, we could go even lower. On both sides (the API could read the value from the node after connection established).
> 
> 
> 
> Moreover, these defaults could be overridden with a custom value in ESPHome config `api:` section.
> 
> 
> 
> This way we could still keep it snappy for the ones not wanting to save power but need faster decisions.

It's not just the power save mode that affects it. Not an exhaustive list but its also the Wi-Fi settings on the access point, the network settings on the router, the distance from the access point to the device, radio interference.

Which problem are you trying to solve by wanting to disconnect it sooner?

**Comment by nagyrobi** [comment]
I build the central heating of the house, controlling separate zones for each room. I use BTHome sensors spread around the home, and I use a few Ethernet connected ESP32 nodes to gather their broadcasts via BT proxy.

I use another, also Ethernet connected ESP32 to do the heating control itself. It implements PID-controlled thermostats in ESPHome. I retrieve the temperature values through Home Assistant from the other nodes. Home Assistant does a great job by aggregating all the broadcasts from all the BTHome sensors through multiple nodes so fault tolerance on that side is present. I need fast temperature updates (every 10 sec or so) in order the PID algo to follow the regulator valves. These Xiaomi temp sensors are very accurate and they are placed in ideal measurement positions.

However, when this main, heating controller ESP32 node loses connection with Home Assistant (eg. HA upgrade etc.), temperature data stops arriving. I need to properly detect that on the node and use a separate, wired, backup temperature sensor to switch to a fail-safe operation mode (freeze PID calculations etc.) until data from BTHome sensors starts flowing in again.

**Comment by bdraco** [comment]
> However, when this main, heating controller ESP32 node loses connection with Home Assistant (eg. HA upgrade etc.), 

That makes more sense why you wanted to change it based on the power_save_mode.  

Since there are two timeouts, one on each side of the connection, you probably want the one on the esphome home side to be configurable for your use case since you want it to drop the HA connection sooner.  Adjusting it here won't do that. 

For HA upgrades it should be telling the esp it's disconnecting but I'm not sure we actually do that on shutdown, only reload??


> temperature data stops arriving. I need to properly detect that on the node and use a separate, wired, backup temperature sensor to switch to a fail-safe operation mode (freeze PID calculations etc.) until data from BTHome sensors starts flowing in again.

**Comment by bdraco** [comment]
Also it looks like there is a race in the disconnect handler. If we already established the connection but haven't finished the hello process we won't send the disconnect request on shutdown.  

But that's outside the scope of this PR as well

**Comment by bdraco** [comment]
Screenshot 2023-03-05 at 7 23 32 AM

No disconnects overnight with this change

**Comment by bdraco** [comment]
I reverted the last commit since it doesn't seem like we need the additional time and ping frequency of 30s + 2.5x disconnect ratio seems to be low enough to be stable but still switch ble proxies within 75s if one dies

**Comment by bdraco** [comment]
Probably should make it 35s interval so we get close to a 90s disconnect timer since thats about the time we know if the wifi has really dropped or not

**Comment by nagyrobi** [comment]
Another thing that came to my mind is what happens after OTA updating an ESPHome node. Currently my experience is not consistent, sometimes after OTA finishes, the node comes back in HA within a few seconds, but unfortunately more often it's like I have to reload the integration manually in order to get it reconnected in a sane amount of time.

After this patch, what will happen? 90 seconds till reconnection?

**Comment by bdraco** [comment]
If the connection wasn't shutdown cleanly and it comes back up it will send a tcp rst as soon as ha tries to talk over the closed connection and reconnect.  That could take up to 87.5 seconds from when it drops offline to when it reconnects if it doesn't tell ha it's disconnecting. 

We could make it faster by always sending the ping every 35s even if it didn't respond to the last one.  The trade off there is we might end up thinking it's alive a little bit longer (just s few seconds) when it completely goes offline

**Comment by bdraco** [comment]
I think that trade off is likely worth it so I refactored it to always send the ping when we reach the 35s but not reset the response timer

**Comment by bdraco** [comment]
I will have to start the test cycle all over again now though

**Comment by nagyrobi** [comment]
Maybe the node should properly announce that OTA is in progress.

**Comment by bdraco** [comment]
It does seem to call safe_reboot at the end https://github.com/esphome/esphome/blob/df3f13ded884682dfbcbba542d79aedb1e100b0a/esphome/components/ota/ota_component.cpp#L355

**Comment by nagyrobi** [comment]
During OTA, the node doesn't respond to pings... Until now, mostly what happened was that the node went offline in HA before OTA finished. So the safe reboot message didn't reach HA...

**Comment by bdraco** [comment]
> During OTA, the node doesn't respond to pings... Until now, mostly what happened was that the node went offline in HA before OTA finished. So the safe reboot message didn't reach HA...

It should probably send the disconnect request as soon as the ota starts but that's for another issue.

**Comment by bdraco** [comment]
Screenshot 2023-03-05 at 11 24 28 AM

`2023-03-05 21:23:30.721 WARNING (MainThread) [aioesphomeapi.connection] officenew89proxy @ 192.168.107.51: Connection error occurred: [Errno 104] Connection reset by peer`

Still solid

**Comment by bdraco** [comment]
I did an ota and the connection gets reset as expected.  It should get the disconnect request but that doesn't work per your comment above

```
2023-03-05 21:34:07.254 WARNING (MainThread) [aioesphomeapi.connection] officenew89proxy @ 192.168.107.51: Connection error occurred: [Errno 104] Connection reset by peer
2023-03-05 21:34:07.256 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for officenew89proxy @ 192.168.107.51: Connection isn't established yet (ConnectionState.CLOSED)
```

I did see that it tries to reconnect too soon though

**Comment by bdraco** [comment]
Screenshot 2023-03-05 at 1 48 37 PM


Still nice and solid with the lower timer.

**Comment by bdraco** [comment]
Digging into the OTA issue just to be 100% sure its not related

**Comment by bdraco** [comment]
The POE board I just OTA does still ping during the OTA

```
2023-03-05 23:53:17.256 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for officenew89proxy @ 192.168.107.51: Connection isn't established yet (ConnectionState.CLOSED)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/reconnect_logic.py", line 122, in _try_connect
    await self._cli.connect(on_stop=self._on_disconnect, login=True)
  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/client.py", line 258, in connect
    await self._connection.connect(login=login)
  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/connection.py", line 409, in connect
    await self._connect_task
  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/connection.py", line 397, in _do_connect
    await self._connect_hello()
  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/connection.py", line 292, in _connect_hello
    resp = await self.send_message_await_response(hello, HelloResponse)
  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/connection.py", line 600, in send_message_await_response
    res = await self.send_message_await_response_complex(
  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/connection.py", line 581, in send_message_await_response_complex
    self.send_message(send_msg)
  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/connection.py", line 475, in send_message
    raise APIConnectionError(
aioesphomeapi.core.APIConnectionError: Connection isn't established yet (ConnectionState.CLOSED)
```

**Comment by bdraco** [comment]
I do get the disconnect request at the end of the OTA
```
2023-03-05 14:00:05.281 DEBUG (MainThread) [aioesphomeapi.connection] officenew89proxy @ 192.168.107.51: Got message of type <class 'api_pb2.DisconnectRequest'>: 
2023-03-05 14:00:05.281 DEBUG (MainThread) [aioesphomeapi.connection] 192.168.107.51: Sending <class 'api_pb2.DisconnectResponse'>: 
2023-03-05 14:00:05.281 DEBUG (MainThread) [aioesphomeapi._frame_helper] Sending frame 776ff4cc8c84d167631a2f5f12f7e21d72e86ef6
2023-03-05 14:00:05.282 DEBUG (MainThread) [aioesphomeapi.connection] Cleaning up connection to officenew89proxy @ 192.168.107.51
2023-03-05 14:00:05.283 DEBUG (MainThread) [aioesphomeapi.connection] Cleaning up connection to officenew89proxy @ 192.168.107.51
2023-03-05 14:00:05.283 INFO (MainThread) [aioesphomeapi.reconnect_logic] Disconnected from ESPHome API for officenew89proxy @ 192.168.107.51
2023-03-05 14:00:05.285 WARNING (MainThread) [switchbot.devices.device]  (C6:D5:B5:C1:2A:22): Device unexpectedly disconnected; RSSI: -58
2023-03-05 14:00:05.286 WARNING (MainThread) [switchbot.devices.device]  (DE:71:80:ED:5F:9E): Device unexpectedly disconnected; RSSI: -80
2023-03-05 14:00:05.289 DEBUG (MainThread) [aioesphomeapi.connection] officenew89proxy @ 192.168.107.51: Connecting to 192.168.107.51:6053 (AddrInfo(family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, proto=6, sockaddr=IPv4Sockaddr(address='192.168.107.51', port=6053)))
2023-03-05 14:00:05.293 DEBUG (MainThread) [aioesphomeapi.connection] 192.168.107.51: Opened socket
2023-03-05 14:00:05.294 DEBUG (MainThread) [aioesphomeapi._frame_helper] Sending frame 
2023-03-05 14:00:05.536 DEBUG (MainThread) [aioesphomeapi.reconnect_logic] officenew89proxy @ 192.168.107.51: Triggering reconnect because of received mDNS record record[ptr,in,_esphomelib._tcp.local.]=0/0,officenew89proxy._esphomelib._tcp.local.
```

**Comment by bdraco** [comment]
I think its too fast. We are actually reconnecting before the esp reboots after the OTA

**Comment by bdraco** [comment]
What happens with the OTA is we reconnect too soon and than the device reboots

https://github.com/esphome/aioesphomeapi/pull/397 will fix that by adding a 3s cooldown

**Comment by bdraco** [comment]
Doing some more testing. I think we should lower the ping since interval to 20s so we still reconnect nearly immediately after reboot and raise the timeout to 4.5.  Thats seems to be the sweet spot as reboots+wifi connect is slight under 20s and poor connections can take no longer than 90s to respond

**Comment by bdraco** [comment]
`2023-03-06 00:50:37.004 WARNING (MainThread) [aioesphomeapi.connection] maui_es015_tb_a @ 192.168.107.204: Connection error occurred: Timeout waiting for response for <class 'api_pb2.ConnectRequest'> after 10.0s` looks like this one is still a bit aggressive on the timeout

**Comment by bdraco** [comment]
I've been beating this up a bit more and everything seems great. I pushed it to all my production systems that run dev

**Comment by raccettura** [comment]
I think this might be related/relevant:

I've got two identical esphome devices (air gradients), one running 2022.9, and one running 2023.2. The 2023.2 seems to have quite a few more disconnects since upgrading. Prior to 2023.2 they were both on 2022.9 and both just had occasional disconnects about the same per device.  So something changed between these two versions that had a negative impact on connection stability.

**Comment by bdraco** [comment]
What message do you get in the log when it disconnects?

**Comment by raccettura** [comment]
I've had trouble gathering that thus far. It happens a few times a day, but I've never been connected by USB when it happens yet.

**Comment by bdraco** [comment]
What do you see in the HA logs?

**Comment by raccettura** [comment]
With the latest release (I was looking at this over the weekend) nothing specific in the logs.  NaN for values in the UI, entities unavailable. After several minutes everything comes back as if nothing happened.

I can double check this tonight as I should have at least a few days worth of logs at this point.

**Comment by raccettura** [comment]
Here's one that I see in the logs:
```
2023-03-07 11:26:53.170 WARNING (MainThread) [aioesphomeapi.connection] air-gradient-bedroom @ 10.10.1.14: Connection error occurred: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/connection.py", line 537, in send_message_await_response_complex
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/connection.py", line 536, in send_message_await_response_complex
    async with async_timeout.timeout(timeout):
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/connection.py", line 320, in _keep_alive_loop
    await self._ping()
  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/connection.py", line 645, in _ping
    await self.send_message_await_response(PingRequest(), PingResponse)
  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/connection.py", line 554, in send_message_await_response
    res = await self.send_message_await_response_complex(
  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/connection.py", line 539, in send_message_await_response_complex
    raise TimeoutAPIError(
aioesphomeapi.core.TimeoutAPIError: Timeout waiting for response for <class 'api_pb2.PingRequest'> after 10.0s
```

**Comment by bdraco** [comment]
> Here's one that I see in the logs:
> 
> ```
> 2023-03-07 11:26:53.170 WARNING (MainThread) [aioesphomeapi.connection] air-gradient-bedroom @ 10.10.1.14: Connection error occurred: 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/connection.py", line 537, in send_message_await_response_complex
>     await fut
> asyncio.exceptions.CancelledError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/connection.py", line 536, in send_message_await_response_complex
>     async with async_timeout.timeout(timeout):
>   File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 129, in __aexit__
>     self._do_exit(exc_type)
>   File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 212, in _do_exit
>     raise asyncio.TimeoutError
> asyncio.exceptions.TimeoutError
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/connection.py", line 320, in _keep_alive_loop
>     await self._ping()
>   File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/connection.py", line 645, in _ping
>     await self.send_message_await_response(PingRequest(), PingResponse)
>   File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/connection.py", line 554, in send_message_await_response
>     res = await self.send_message_await_response_complex(
>   File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/connection.py", line 539, in send_message_await_response_complex
>     raise TimeoutAPIError(
> aioesphomeapi.core.TimeoutAPIError: Timeout waiting for response for <class 'api_pb2.PingRequest'> after 10.0s
> ```

That the old code. Can you try with 2023.3.2?

**Comment by raccettura** [comment]
Rebooted with 2023.3.2 about 5m after posting that.  Will keep an eye out to see what happens.

**Comment by raccettura** [comment]
I didn't forget about this.  I let it run for a few days to observe what happens.  Not once did I notice a disconnect on either the 2022.9 or 2023.2 epshome instance.  Only things I saw in the past few days is:

```
2023-03-08 23:37:19.146 WARNING (MainThread) [aioesphomeapi.connection] air-gradient-livingroom @ 10.10.1.13: Connection error occurred: Ping response not received after 90.0 seconds
2023-03-08 23:37:19.885 WARNING (MainThread) [aioesphomeapi.connection] air-gradient-bedroom @ 10.10.1.14: Connection error occurred: Ping response not received after 90.0 seconds
2023-03-08 23:37:52.985 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for air-gradient-bedroom @ 10.10.1.14: Handshake timed out
2023-03-08 23:37:52.985 WARNING (MainThread) [aioesphomeapi.connection] air-gradient-bedroom @ 10.10.1.14: Connection error occurred: Connection lost
2023-03-09 15:19:39.273 WARNING (MainThread) [aioesphomeapi.connection] air-gradient-bedroom @ 10.10.1.14: Connection error occurred: EOF received
2023-03-09 15:20:09.288 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for air-gradient-bedroom @ 10.10.1.14: Handshake timed out
2023-03-09 15:20:09.289 WARNING (MainThread) [aioesphomeapi.connection] air-gradient-bedroom @ 10.10.1.14: Connection error occurred: Connection lost
2023-03-10 03:04:58.662 WARNING (MainThread) [aioesphomeapi.connection] air-gradient-livingroom @ 10.10.1.13: Connection error occurred: [Errno 104] Connection reset by peer
2023-03-10 22:57:52.563 WARNING (MainThread) [aioesphomeapi.connection] air-gradient-livingroom @ 10.10.1.13: Connection error occurred: Ping response not received after 90.0 seconds
2023-03-11 22:08:32.017 WARNING (MainThread) [aioesphomeapi.connection] air-gradient-livingroom @ 10.10.1.13: Connection error occurred: [Errno 104] Connection reset by peer
2023-03-12 09:39:24.118 WARNING (MainThread) [aioesphomeapi.connection] air-gradient-livingroom @ 10.10.1.13: Connection error occurred: Ping response not received after 90.0 seconds
2023-03-12 09:39:27.188 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for air-gradient-livingroom @ 10.10.1.13: Error connecting to ('10.10.1.13', 6053): [Errno 113] Connect call failed ('10.10.1.13', 6053)
2023-03-13 01:08:36.156 WARNING (MainThread) [aioesphomeapi.connection] air-gradient-livingroom @ 10.10.1.13: Connection error occurred: Ping response not received after 90.0 seconds
2023-03-13 01:08:39.220 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for air-gradient-livingroom @ 10.10.1.13: Error connecting to ('10.10.1.13', 6053): [Errno 113] Connect call failed ('10.10.1.13', 6053)
2023-03-13 12:08:12.289 WARNING (MainThread) [aioesphomeapi.connection] air-gradient-bedroom @ 10.10.1.14: Connection error occurred: EOF received

```

So while my logs aren't clean, I can confirm there's a substantial improvement with 2023.3.2.

**Comment by bdraco** [comment]
Great. It looks much better. It looks like `air-gradient-bedroom` is being disconnected from the network (maybe even crashing?) though.

**Comment by raccettura** [comment]
I'm really not sure what's going on there.  I was thinking of adding the uptime sensor to make it easier to see if it's crashing.  I don't see evidence from a network dropoff at least from the network side of things.

**Comment by nagyrobi** [comment]
You may experience strong interference at that location. Try moving it in another place.

**Comment by raccettura** [comment]
Bumped both sensors to 2023.3.0, enabled uptime sensor.

**Comment by bdraco** [comment]
I'll get https://github.com/esphome/aioesphomeapi/pull/401 pushed out as well.  That should give you a bit more leeway before disconnects

**Comment by raccettura** [comment]
I'll keep an eye out for that and report back.

**Pull request merged**
