### PR TITLE
Optimize throughput of api to decrease latency

### PR DESCRIPTION
**Pull request by bdraco**
We still have a bit of latency with the reader because we have to lock and unlock every loop. Once we have finished the handshake (noise only) we hold the read lock for the duration of the connection to avoid locking/unlocking on every read

### CODE REVIEW

**Comment by bdraco** [comment]
Why does this have a write lock when we only write full packets?

**Comment by bdraco** [comment]
At some point this was all refactored so writes go though a single place.

Since we are writing to a buffered stream there isn't much point in holding the lock as long as we do a single pack in a single write

**Comment by bdraco** [comment]
It looks like we are only draining as well so we can catch the socket errors

**Comment by bdraco** [comment]
Need to enable noise and test that

**Comment by bdraco** [comment]
Well thats way better

```
2022-12-01 23:49:04.374 DEBUG (MainThread) [aiohomekit.controller.ble.pairing] Nanoleaf A19 0VLK [E3:D8:3F:82:3A:AF] (id=3D:B8:16:2A:B2:3E): Finished _async_subscribe, checking for subscription restore: False
2022-12-01 23:49:04.681 DEBUG (MainThread) [aiohomekit.controller.ble.pairing] Nanoleaf A19 0VLK [E3:D8:3F:82:3A:AF] (id=3D:B8:16:2A:B2:3E): Subscribing to gatt notify for iid: 53
2022-12-01 23:49:04.703 DEBUG (MainThread) [aiohomekit.controller.ble.pairing] Nanoleaf A19 0VLK [E3:D8:3F:82:3A:AF] (id=3D:B8:16:2A:B2:3E): Subscribing to gatt notify for iid: 117
2022-12-01 23:49:04.755 DEBUG (MainThread) [aiohomekit.controller.ble.pairing] Nanoleaf A19 0VLK [E3:D8:3F:82:3A:AF] (id=3D:B8:16:2A:B2:3E): Subscribing to gatt notify for iid: 52
2022-12-01 23:49:04.813 DEBUG (MainThread) [aiohomekit.controller.ble.pairing] Nanoleaf A19 0VLK [E3:D8:3F:82:3A:AF] (id=3D:B8:16:2A:B2:3E): Subscribing to gatt notify for iid: 55
2022-12-01 23:49:04.866 DEBUG (MainThread) [aiohomekit.controller.ble.pairing] Nanoleaf A19 0VLK [E3:D8:3F:82:3A:AF] (id=3D:B8:16:2A:B2:3E): Subscribing to gatt notify for iid: 51
2022-12-01 23:49:04.918 DEBUG (MainThread) [aiohomekit.controller.ble.pairing] Nanoleaf A19 0VLK [E3:D8:3F:82:3A:AF] (id=3D:B8:16:2A:B2:3E): Subscribing to gatt notify for iid: 54
```

Can almost get a subscribe down to 50ms

**Comment by bdraco** [comment]
```
2022-12-01 23:52:39.012 DEBUG (MainThread) [aiohomekit.controller.ble.pairing] Eve Button F17F [DB:CE:11:02:F9:44] (id=11:18:37:A4:93:51): Subscribing to gatt notify for iid: 34
2022-12-01 23:52:39.049 DEBUG (MainThread) [aiohomekit.controller.ble.pairing] Eve Button F17F [DB:CE:11:02:F9:44] (id=11:18:37:A4:93:51): Subscribing to gatt notify for iid: 35
2022-12-01 23:52:39.091 DEBUG (MainThread) [aiohomekit.controller.ble.pairing] Eve Button F17F [DB:CE:11:02:F9:44] (id=11:18:37:A4:93:51): Subscribing to gatt notify for iid: 19
2022-12-01 23:52:39.134 DEBUG (MainThread) [aiohomekit.controller.ble.pairing] Eve Button F17F [DB:CE:11:02:F9:44] (id=11:18:37:A4:93:51): Subscribing to gatt notify for iid: 36
```

**Comment by bdraco** [comment]
Works great with noise

Reauth doesn't actually work right in HA as it just aborts when you switch from no encryption to encryption, but thats a problem on the HA side.  Delete and re-setup works though.

**Review by balloob — APPROVED** [review]

**Pull request merged**
