### PR TITLE
Add Humidifier component

### PR DESCRIPTION
**Pull request by alevaquero**
This adds a Humidifier component which is copy/mimic most of the Climate component functionality. I've assigned IDs 66 to 68 in the api.proto as there are some in-flight IDs used for MediaPlayer (63-65)

Related ESPHome PR https://github.com/esphome/esphome/pull/3523
Related HA core PR https://github.com/home-assistant/core/pull/72946

### CODE REVIEW

**Comment by nagyrobi** [comment]
https://github.com/esphome/feature-requests/issues/1859

**Review by jesserockz — CHANGES_REQUESTED** [review]
Please rebase this and then change the message ids to start at 80 (I am working on a few for bluetooth that go up to 76 and might need a few more)

**Comment by nagyrobi** [comment]
@alevaquero

**Comment by bdraco** [comment]
This one is now a year old and has gone stale. If you want to move this forward, please reopen / start a new PR

**Pull request closed without merging**
